
spring:
  application:
    name: spring-cloud-stream-producer
  cloud:
    stream:
      binders:
        shiayangaBinder:
          type: rabbit
          environment:
            spring:
              rabbitmq: localhost
              port: 5672
              username: admin
              password: admin
      bindings:
        output:
          destination: shiayangaExchange
          content-type: text/plain
          binder: shiayangaBinder
        outputLog:
          destination: inputLog
          content-type: text/plain
          binder: shiayangaBinder
server:
  port: 9090
